[program:spug-mcp]
command = sh /data/spug/spug_api/tools/start-mcp.sh
autostart = true
autorestart = true
startsecs = 3
stdout_logfile = /data/spug/spug_api/logs/mcp.log
redirect_stderr = true
stopasgroup = true
killasgroup = true
