# Generated by Django 3.2.25 on 2026-08-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrecord',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agentrecord',
            name='kind',
            field=models.CharField(choices=[('context', '任务上下文'), ('question', '用户提问'), ('answer', 'AI回复'), ('thought', 'AI分析'), ('command', '执行命令'), ('output', '命令输出'), ('verify', '结果复检'), ('summary', '最终结论'), ('error', '异常')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='mode',
            field=models.CharField(choices=[('chat', '问答'), ('diagnose', 'AI诊断'), ('repair', 'AI修复')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('running', '执行中'), ('success', '已完成'), ('failed', '未解决'), ('error', '执行异常')], default='running', max_length=20),
        ),
    ]
