# Generated by Django 3.2.25 on 2026-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_mcp_skill_context_compress'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='messages',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='sdk_version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
