# Generated by Django 4.2.30 on 2026-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_alter_agentsession_max_loops'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='target_scope',
            field=models.TextField(null=True),
        ),
    ]
