# Generated by Django 4.2.30 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='connect_timeout',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='query_timeout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='idle_timeout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='environment',
            field=models.CharField(choices=[('normal', '普通环境'), ('production', '生产环境')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
