# Generated by Django 4.2.30 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='connect_timeout',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='query_timeout',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
