# Generated by Django 4.2.30 on 2026-09-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_task_ai_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '执行中'), (1, '成功'), (2, '失败'), (3, '已中断')]),
        ),
    ]
