# Generated by Django 3.2.25 on 2026-08-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='ai_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='host.host'),
        ),
        migrations.AddField(
            model_name='detection',
            name='ai_max_loops',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='detection',
            name='ai_mode',
            field=models.CharField(choices=[('', '不启用'), ('diagnose', 'AI诊断'), ('repair', 'AI修复')], default='', max_length=20),
        ),
    ]
