# Generated by Django 4.2.30 on 2026-09-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20260830_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='type',
            field=models.CharField(choices=[('1', '站点检测'), ('2', '端口检测'), ('3', '进程检测'), ('4', '自定义脚本'), ('5', 'Ping检测'), ('6', 'Docker服务检测')], max_length=2),
        ),
    ]
