# Generated by Django 3.2.25 on 2026-08-30 21:33

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_url', models.CharField(max_length=255)),
                ('api_key', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('timeout', models.IntegerField(default=600)),
                ('temperature', models.FloatField(default=0.2)),
                ('sort_id', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ('-is_default', '-sort_id', 'id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('manual', '手动发起'), ('monitor', '监控告警')], default='manual', max_length=20)),
                ('mode', models.CharField(choices=[('diagnose', 'AI诊断'), ('repair', 'AI修复')], max_length=20)),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '已完成'), ('failed', '未解决'), ('error', '执行异常')], default='running', max_length=20)),
                ('detection_id', models.IntegerField(null=True)),
                ('target', models.CharField(max_length=255, null=True)),
                ('trigger_message', models.TextField(null=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('max_loops', models.IntegerField(default=3)),
                ('used_loops', models.IntegerField(default=0)),
                ('summary', models.TextField(null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('finished_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='host.host')),
            ],
            options={
                'db_table': 'agent_sessions',
                'ordering': ('-id',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='AgentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('context', '任务上下文'), ('thought', 'AI分析'), ('command', '执行命令'), ('output', '命令输出'), ('verify', '结果复检'), ('summary', '最终结论'), ('error', '异常')], max_length=20)),
                ('content', models.TextField()),
                ('extra', models.TextField(null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ai.agentsession')),
            ],
            options={
                'db_table': 'agent_records',
                'ordering': ('id',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
