# Generated by Django 3.2.25 on 2026-08-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20260830_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='pending',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agentrecord',
            name='kind',
            field=models.CharField(choices=[('context', '任务上下文'), ('question', '用户提问'), ('answer', 'AI回复'), ('thought', 'AI分析'), ('command', '执行命令'), ('confirm', '待确认命令'), ('output', '命令输出'), ('verify', '结果复检'), ('summary', '最终结论'), ('error', '异常')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('running', '执行中'), ('waiting', '等待确认'), ('success', '已完成'), ('failed', '未解决'), ('error', '执行异常')], default='running', max_length=20),
        ),
    ]
