# Generated by Django 4.2.30 on 2026-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_auto_20260902_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='max_loops',
            field=models.IntegerField(default=30),
        ),
    ]
